// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZIGwYWMsLuvNZ0PpFP6bwt9s4IB-bLP8',
    appId: '1:489539373810:web:17e09dd6b1ae95d7665e6b',
    messagingSenderId: '489539373810',
    projectId: 'e-learning-platform-10cd6',
    authDomain: 'e-learning-platform-10cd6.firebaseapp.com',
    storageBucket: 'e-learning-platform-10cd6.firebasestorage.app',
    measurementId: 'G-KB09DPP6Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuLHdHjtDQtLZVw01GjFCUw0Ue0rYMPvg',
    appId: '1:489539373810:android:a6abbdc59919bd0a665e6b',
    messagingSenderId: '489539373810',
    projectId: 'e-learning-platform-10cd6',
    storageBucket: 'e-learning-platform-10cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdf9yQyU5S189jT2v5w-_e3lfIpuNiSmU',
    appId: '1:489539373810:ios:ebe359c9bab44f03665e6b',
    messagingSenderId: '489539373810',
    projectId: 'e-learning-platform-10cd6',
    storageBucket: 'e-learning-platform-10cd6.firebasestorage.app',
    iosBundleId: 'com.example.trainingAcedamy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdf9yQyU5S189jT2v5w-_e3lfIpuNiSmU',
    appId: '1:489539373810:ios:ebe359c9bab44f03665e6b',
    messagingSenderId: '489539373810',
    projectId: 'e-learning-platform-10cd6',
    storageBucket: 'e-learning-platform-10cd6.firebasestorage.app',
    iosBundleId: 'com.example.trainingAcedamy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZIGwYWMsLuvNZ0PpFP6bwt9s4IB-bLP8',
    appId: '1:489539373810:web:17e09dd6b1ae95d7665e6b',
    messagingSenderId: '489539373810',
    projectId: 'e-learning-platform-10cd6',
    authDomain: 'e-learning-platform-10cd6.firebaseapp.com',
    storageBucket: 'e-learning-platform-10cd6.firebasestorage.app',
    measurementId: 'G-KB09DPP6Z0',
  );

}